API Change: `emitter.tell` now takes in `add_statuses` and `add_values`
icaros-usc/pyribs pull request #227
Opened 2022-07-06 15:32 UTC by itsdawei

## Description

`emitter.tell` now takes in `add_statuses` and `add_values`

## TODO

- [ ] `emitter.tell`
- [ ] `optimizer.tell`

## Status

- [ ] I have read the guidelines in [CONTRIBUTING.md](https://github.com/icaros-usc/pyribs/blob/master/CONTRIBUTING.md).
- [ ] I have formatted my code using `yapf`
- [ ] I have tested my code by running `pytest`
- [ ] I have linted my code with `pylint`
- [ ] I have added a one-line description of my change to the changelog in `HISTORY.md`.
- [ ] This PR is ready to go

2022-07-09 03:29 UTC, btjanaka requested changes

2022-07-09 03:29 UTC, btjanaka commented on ribs/_docstrings.py
> +    status_batch (numpy.ndarray): 1D array of :class:`ribs.archive.AddStatus`
say it's an array of "integer statuses" since I don't return AddStatus from the batched addition (you can't make a NumPy array that has Python enums)

2022-07-09 03:29 UTC, btjanaka commented on ribs/emitters/_emitter_base.py
> +                :class:`ribs.archive.AddStatus` returned by a series of calls to
same comment about statuses

2022-07-09 03:29 UTC, btjanaka commented on ribs/emitters/_emitter_base.py
> +             solutions,
Use the batch terminology here with `solution_batch`, `objective_batch`, `measures_batch`, `metadata_batch`

2022-07-09 03:29 UTC, btjanaka commented on ribs/emitters/_gaussian_emitter.py
> +        for sol, obj, beh, meta in zip(solutions, objective_values,
How come we're still adding here?

2022-07-09 03:29 UTC, btjanaka commented on ribs/emitters/_iso_line_emitter.py
> +        for sol, obj, beh, meta in zip(solutions, objective_values,
shouldn't need to add here either

2022-07-09 03:29 UTC, btjanaka commented on ribs/optimizers/_optimizer.py
> +    def tell(self, objective_batch, measures_batch, metadata=None):
`metadata_batch`

2022-07-09 03:29 UTC, btjanaka commented on ribs/optimizers/_optimizer.py
>                  emitter.tell(self._solutions[pos:end],
Rename `self._solutions` to `self._solution_batch`

2022-07-09 03:29 UTC, btjanaka commented on tests/emitters/evolution_strategy_emitter_test.py
> +        status_batch = []
we'll have to remember to shorten this once we get add_batch -- can you create a TODO?

2022-07-11 08:53 UTC, itsdawei reviewed
Self-review

2022-07-12 05:18 UTC, btjanaka approved these changes

2022-07-12 05:18 UTC, btjanaka commented on tests/emitters/conftest.py
> +    def add(self, solution, objective_value, measures_value, metadata=None):
Just use `objective` and `measures`

2022-07-12 05:18 UTC, btjanaka commented on ribs/_docstrings.py
> +        archive's :meth:`add_batch()`. For what these floats represent,
`add` and `add_single`

2022-07-12 05:18 UTC, btjanaka commented on ribs/emitters/_emitter_base.py
> +                array with the measures space coordinates of each solution.
`measure space` not `measures space`

2022-07-12 05:18 UTC, btjanaka commented on ribs/emitters/_emitter_base.py
> +                method or by a single call to archive's :meth:`add_batch()`.
`add` and `add_single`

2022-07-12 05:18 UTC, btjanaka commented on ribs/emitters/_gaussian_emitter.py
> +            value_batch  (numpy.ndarray): 1D array of floats returned by a
`add` and `add_single`

2022-07-12 05:18 UTC, btjanaka commented on ribs/emitters/_iso_line_emitter.py
> +                series of calls to archive's :meth:`add()` method or by a single
`add` and `add_single`

2022-07-12 11:25 UTC, itsdawei commented
TODO Add performance score

2022-07-12 12:52 UTC, itsdawei commented
> Algorithm 	New Implementation
> cma_me_imp 	90.640%, 17299781 QD, 124s
> cma_me_imp_mu 	92.471%, 17663709 QD, 113s
> cma_me_rd 	95.877%, 13965477 QD, 107s
> cma_me_rd_mu 	96.952%, 13200075 QD, 113s
> cma_me_opt 	11.170%, 2446958 QD, 149s
> cma_me_mixed 	95.685%, 17953962 QD, 158s

2022-07-12 13:02 UTC, merged